### ISSUE TITLE
Generate Bash Tags Error

### ISSUE THREAD

**Issue by yetihairball** [fireundubh/xedit#2]
Script stops with error:

'unit' expected but '<' found.

**Comment by PythonDad** [comment]
Bumping this. Were you able to figure anything out? I'm having this exact issue, and so are many others. There seem to be no fixes forthcoming.

**Comment by yetihairball** [comment]
No solutions found, yet.  No support from here.  I found this script works better with older versions of TSVEdit, but would still throw errors occasionally.

**Comment by fireundubh** [comment]
Can you provide more information?

- Name of game
- Name of plugin you're running the script on
- List of loaded plugins
- Version of the script
- Whether mteFunctions is installed
- Version of mteFunctions
- Whether dubhFunctions is installed
- Log of successful bash tag tests
- Options selected when prompted

Not much I can do with what you posted until I have more information.

**Comment by PythonDad** [comment]
Sorry for the late reply. Was doing new year stuff.

Fallout: New Vegas
A merged cut content plugin made with Merge Plugins
Only plugins loaded are the FalloutNV.esm, FalloutNV.exe, and the above plugin
I'm using the version of the script here: https://github.com/fireundubh/xedit/tree/master/all
mteFunctions I'm using is the one here https://github.com/matortheeternal/mxpf/tree/master/Edit%20Scripts/lib
Using the dubhFunctions here https://github.com/fireundubh/xedit/tree/master/lib

I'm kind of new to this, what do I need to do to get a log of successful bash tag tests?

**Comment by fireundubh** [comment]
When you run the script, click the Yes button when the second confirmation prompt is displayed.

Throw that plugin up somewhere, too.

**Comment by PythonDad** [comment]
Maybe I'm doing something wrong?

![fnvedit](https://cloud.githubusercontent.com/assets/24849321/21583428/51a2fff0-d04e-11e6-86ef-dd1e917ccf30.png)

I click OK and then I get this:

![fnvedit2](https://cloud.githubusercontent.com/assets/24849321/21583429/6c3e969e-d04e-11e6-8311-76a7a1d46ad5.png)

**Comment by fireundubh** [comment]
Is `mteFunctions.pas` and `dubhFunctions.pas` in the same folder as `Generate Tags for Wrye Bash.pas`?

**Comment by PythonDad** [comment]
Yes.

**Comment by fireundubh** [comment]
You didn't save the scripts correctly. You can clearly see HTML in your first screenshot.

They need to be saved as plain text:

* [Generate Tags for Wrye Bash.pas](https://raw.githubusercontent.com/fireundubh/xedit/master/all/Generate%20Tags%20for%20Wrye%20Bash.pas)
* [mteFunctions.pas](https://raw.githubusercontent.com/matortheeternal/TES5EditScripts/master/Edit%20Scripts/mteFunctions.pas)
* [dubhFunctions.pas](https://raw.githubusercontent.com/fireundubh/xedit/master/lib/dubhFunctions.pas)

**Comment by PythonDad** [comment]
Okay, not sure how that happened, but I will give it a try.

**Comment by yetihairball** [comment]
I am also using this script for New Vegas and loosely following the Fear and Loathing STEP guide.  I am positive I saved these scripts as plain text, but the error makes sense if it is running into an unexpected HTML tag.  Thanks for the response, fireundubh.  This should solve my issues, too.
