### ISSUE TITLE
Error in merge overrides into master script

### ISSUE THREAD

**Issue by RoyBatty64** [fireundubh/xedit#7]
Exception in unit  line -1: Error in unit 'MergeOverridesIntoMaster' on line 94 : Undeclared Identifier 'Items'

Works in 3.2 mainbranch

**Comment by fireundubh** [comment]
What script are you running?

**Comment by fireundubh** [comment]
```delphi
clb := TCheckListBox(frm.FindComponent('CheckListBox1'));
```

That script is failing because `CheckListBox1` is no longer the name of that component. It is `clbPlugins`.

**Comment by fireundubh** [comment]
Fixed the following scripts in bfec9a575824d919eac39fb87fbd176109e783f0:

- Edit Scripts/Copy as override.pas
- Edit Scripts/Copy version control info from another plugin.pas
- Edit Scripts/Merge overrides into master.pas
- Edit Scripts/Report masters.pas
- Edit Scripts/Skyrim - Book Covers Patch.pas
- Edit Scripts/Weather Editor.pas
- Edit Scripts/Worldspace browser.pas
